### ISSUE TITLE
Not Working anymore

### ISSUE THREAD

**Issue by arejay73** [ofstudio/djay2itunes.js#1]
Environment
OS X 10.11.03
iTunes 12.3.2.35
Djay Pro 1.2.1

I have tried reinstalling day pro with no luck.  I have a list of about 110 songs.  The BPM shows up in DJay Pro and the script runs through but does not update files.  Here is the error of one file.  All the files have the same error.

app = Application("System Events")
    app.propertyListFiles.byName("~/Library/Containers/com.algoriddim.djay-pro-mac/Data/Library/Application Support/Algoriddim/djay Preset Library.plist").propertyListItems.byName("Song Entries").propertyListItems.byName("one day\tkt tunstall\t302").value()
        --> Error -1728: Can't get object.
    app.propertyListFiles.byName("~/Library/Containers/com.algoriddim.djay-pro-mac/Data/Library/Application Support/Algoriddim/djay Preset Library.plist").propertyListItems.byName("Song Entries").propertyListItems.byName("2BA7E7D173FDD37B").value()
        --> Error -1728: Can't get object.
    app.propertyListFiles.byName("~/Library/Containers/com.algoriddim.djay-pro-mac/Data/Library/Application Support/Algoriddim/djay Cached Data.plist").propertyListItems.byName("one day\tkt tunstall\t302").value()
        --> Error -1728: Can't get object.
    app.propertyListFiles.byName("~/Library/Containers/com.algoriddim.djay-pro-mac/Data/Library/Application Support/Algoriddim/djay Cached Data.plist").propertyListItems.byName("2BA7E7D173FDD37B").value()
        --> Error -1728: Can't get object.
    app.propertyListFiles.byName("~/Library/Containers/com.algoriddim.djay-pro-mac/Data/Library/Application Support/Algoriddim/djay Preset Library.plist").propertyListItems.byName("Song Entries").propertyListItems.byName("one day\tkt tunstall\t302").value()
        --> Error -1728: Can't get object.
    app.propertyListFiles.byName("~/Library/Containers/com.algoriddim.djay-pro-mac/Data/Library/Application Support/Algoriddim/djay Preset Library.plist").propertyListItems.byName("Song Entries").propertyListItems.byName("2BA7E7D173FDD37B").value()
        --> Error -1728: Can't get object.
    app.propertyListFiles.byName("~/Library/Containers/com.algoriddim.djay-pro-mac/Data/Library/Application Support/Algoriddim/djay Cached Data.plist").propertyListItems.byName("one day\tkt tunstall\t302").value()
        --> Error -1728: Can't get object.
    app.propertyListFiles.byName("~/Library/Containers/com.algoriddim.djay-pro-mac/Data/Library/Application Support/Algoriddim/djay Cached Data.plist").propertyListItems.byName("2BA7E7D173FDD37B").value()
        --> Error -1728: Can't get object.

**Comment by ofstudio** [comment]
This looks very strange.
Can you share 

`~/Library/Containers/com.algoriddim.djay-pro-mac/Data/Library/Application Support/Algoriddim/djay Cached Data.plist`

and

`~/Library/Containers/com.algoriddim.djay-pro-mac/Data/Library/Application Support/Algoriddim/djay Preset Library.plist`

?

**Comment by arejay73** [comment]
[djayData.zip](https://github.com/ofstudio/djay2itunes.js/files/104934/djayData.zip)

**Comment by arejay73** [comment]
I did a rescan of my entire library.  And ran script against my playlist of NoBPM files and it picked up an additional 4 files, but skipped the rest with the same error.  Here are the refreshed files.
[djayData2.zip](https://github.com/ofstudio/djay2itunes.js/files/105566/djayData2.zip)

**Comment by arejay73** [comment]
Any updates on this?  Do you need more information?

**Comment by ofstudio** [comment]
Your djay database files seems to be ok.

Perhaps the problem in the wrong determining the length of the track. The djay database identifies each track one of two ways (don't know why)
1. By "iTunes Persistent ID" – an internal iTunes unique song identifier (in your example above this is `2BA7E7D173FDD37B`)
2. …or by "song slug" – a  string consisting of three fields separated by tab (`\t`) symbol
   - **Title** of the track (in lowercase)
   - **Artist** (lowercased too)
   - **Duration**  of the track in seconds (_rounded(!)_ to 1 second)
   
   In your example this is `one day\tkt tunstall\t302` string (which means "One Day by KT Tunstall with duration about 5 min 02 sec")

djay2itunes tries to get info about the song from djay database using _both_ ways:
1. Search song with  appropriate iTunes Persistent ID in djay database
2. If record with such iTunes Persistent ID exists in database – get BPM and key values and write them to iTunes 
2. If no record with given  iTunes Persistent ID found — try to find record by "song slug"

And the problem is to build correct "song slug" (title+artist+duration). Because djay determines duration of the track slightly different than iTunes. And sometimes track duration in iTunes and in djay differs in 1 second up or down and djay2itunes can not build a valid "song slug" and thus can not find the track in djay database.

In my case, it happens very rarely.  But in your case dj2itunes tries to search `one day\tkt tunstall\t302` but in djay database the record is `one day\tkt tunstall\t303` (1 second differs). 

The solution is to build 2 slugs with ±1 sec duration field, and try to search both of them.

Check for [update](https://github.com/ofstudio/djay2itunes.js/releases/download/v0.0.4/djay2itunes.app.zip). Hope this helps

**Comment by arejay73** [comment]
Tried this last night and it worked.  It processed all of my outstanding files.  Thanks.
